### ISSUE TITLE
PAS photodiode and arms signals not showing in UI 

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#101]
I know you know about this one but just adding it to the list. Basically signals for the photodiodes and arms are in MAX but don't appear in the UI plots

**Comment by lo-co** [comment]
What is "arms"?

Photodiode signals are being broadcast -they are near zero (< 1) and were converting from floats to I16.  This meant that all were rounded to zero.  The values for this will be between ~+/-32k.

**Comment by lo-co** [comment]
All is well with this.  Closing with no check-in.
