### ISSUE TITLE
Big delay on waveform plots

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#102]
Have noticed that the waveform plots are running around 4-5 seconds behind actual events. I.e. I change the laser power on a CRDS channel and the PMT shows the change 4-5 seconds later.

This is a different issue to #94 as it happens even when plots are updating regularly each second.  

Can this delay time be shortened. Optical cell alignment will be hard with this delay

**Comment by JustinLangridge** [comment]
Can we bump this up the priority list please Matt. As we currently stand we can't use the UI for alignments as the delay time is too long. 

Dave has had a look and thinks the issue might be introduced at startup where we start to put data in buffers before it is read out and thus introduce a lag. Help needed to fix this though.

**Comment by lo-co** [comment]
Data is not buffered so this is not the issue.

**Comment by lo-co** [comment]
So, this is actually a server issue.  The jiggering of all of the PMT outputs has really kind of hosed things.  See lo-co/exscalabar_server#145.

**Comment by lo-co** [comment]
I can't actually see an issue with this.  I can match times with the stamp that is part of the CRD data structure and that on the front panel.  The client side does not buffer.  I think this is something that we are going to have to look at closely together tomorrow.
