### ISSUE TITLE
Add O3 Valve Button

### ISSUE THREAD

**Issue by lo-co** [lo-co/exscalabar#103]
Backend should be present.  Just do it...

**Comment by lo-co** [comment]
Button is added.

**Comment by JustinLangridge** [comment]
Not sure if we are expecting this to work yet? It works from MAX, but not from the new button currently.

**Comment by lo-co** [comment]
Not yet

**Comment by lo-co** [comment]
Justin, this should be ready for testing.  The valve values should be as follows:

* ``TRUE`` or high - open
* ``FALSE`` or low - closed

So, initially this value should be ``FALSE`` - I close this at the beginning.  The values may be backwards so check to make sure the functionality is as you desire.

**Comment by JustinLangridge** [comment]
Tested and confirm that this is functioning correctly. Closing.
