### ISSUE TITLE
Add UI indicator linked to pump blockage

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#104]
When the sample pump block signal on the CRD_HK card goes high it indicates that the system has been pumped down below ~200mbar causing the sample pump to be automatically shut off.

Need to add indicator to the UI to indicate this has happened. Logging of this signal is not required.

**Comment by lo-co** [comment]
Added check for pump blockage (``Data.data.pBlocked``).  Expose indicator even with no blockage.  Indicator will say 

* ``Pump Clear`` if ``FALSE``
* ``Pump Blocked!`` if ``TRUE``
