### ISSUE TITLE
Change CVT/Data Retrieval Rate

### ISSUE THREAD

**Issue by lo-co** [lo-co/exscalabar#107]
The fixed 1 second is making things more difficult, especially for cell alignment.  The server will have to be synced so that when the data string is the same, the json object will be empty (similar to what we do with the cvt).

**Comment by lo-co** [comment]
Changed this to 100 ms and all seems ok.  

This checks to see if the data has changed.  If it hasn't, then the status code is set to ``204``.  If the data ID array is empty then the status code is set to ``209``.

**Comment by JustinLangridge** [comment]
Not sure if this is the cause but the system is now having issues with update rates. The UI clock is not ticking along each second, but stops and starts, often jumping on several seconds. 

Several system restarts have not helped.

**Comment by JustinLangridge** [comment]
Dave has changed this back to 1000ms which has reverted back to normal behaviour. Needs looking at with respect to why it wasn't working with 100ms
