### ISSUE TITLE
PAS time domain data not plotting

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#112]
As seen via team viewer today system is struggling to plot any PAS tie domain data. reason unknown but this has worked in the past.

**Comment by lo-co** [comment]
OK, so this worked in the past because we were dealing with a lot fewer points. I think.

**Comment by lo-co** [comment]
I am closing this.  It is a rendering issue - apparently something is choking when trying to plot 200k points.  I will take a look at that later and try to figure it out.  Right now, I am going to decimate the data by a factor 5 for the microphone data (8k points) and a factor of 2 for the photodiode (5k points).  Let me know if this is a problem.
