### ISSUE TITLE
Style PAS plots

### ISSUE THREAD

**Issue by lo-co** [lo-co/exscalabar#14]
Plots need styling.  

* Plots should be contained within a single column that is centered between the controls and the sidebar.
* Plots need to resize properly.
* Add right-click functionality for 
  * Switching between different data sets
  * Autoscaling.
  * Clearing the plot data (this will have to be connected to the data service so that we can clear the data out)
* Provide easy ability to turn off different plots.

**Comment by mtat76** [comment]
Autoscaling indicates that the scale will automatically adjust to the max and min.  I can't remember if most of these plots automatically autoscale, but we should have an autoscale and and an autoscale 1x option (meaning that the graph autoscales once and then sits at the new max and min until requested differently).

**Comment by mtat76** [comment]
Switching between data sets means exactly what you think - f0 -> Q -> IA, etc, etc...

**Comment by lo-co** [comment]
This was fixed a long time ago.  Closing
