### ISSUE TITLE
Defer all http requests to services

### ISSUE THREAD

**Issue by lo-co** [lo-co/exscalabar#21]
Currently, it looks like a lot of mish-mash of execution in services and controllers.

**Comment by msrconsulting** [comment]
All PAS laser requests are now in the CVT (where implemented).  Using the PAS to test all of this...

**Comment by JustinLangridge** [comment]
This has got a testing flag but not sure what is needed. Is this basically asking to test the PAS functionality? If so we can close this issue and I'll raise new ones based on the testing results if needed

**Comment by lo-co** [comment]
This is mislabeled - it's architectural and transparent to the user.  Ignore this.  I am going to close it.
