### ISSUE TITLE
Add CRD Laser Enable 

### ISSUE THREAD

**Issue by lo-co** [lo-co/exscalabar#33]
CRD needs laser enable buttons.  See issue lo-co/exscalabar_server#31

**Comment by JustinLangridge** [comment]
We've got another issue running for this now - should this one be closed?

**Comment by lo-co** [comment]
This should be closed simply because this is functional.  This is strictly UI related.  The buttons are there and connected.  They are miswired on the server side.  Closing now.  Should have been closed a long time ago.
