### ISSUE TITLE
PAS temperatures

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#79]
Add UI displays for PAS cell thermistrors (perhaps in with the vaisala and honeywell housekeeping data)

**Comment by lo-co** [comment]
So, according to the signal list, there is only one DAQ temperature per cell.  I am going to place these on the PAS plot and the others will go into the Meerstetter plots.

**Comment by lo-co** [comment]
The directive for this is ``ex-pas-temp-plot``.  The file is in ``pas/ex.pastemp.dir.js``.
