### ISSUE TITLE
PAS laser enable signal buttons

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#86]
Pressing the 5 enable/disable buttons on the PAS UI page doesn't do anything. Have probed pins on thePXI 7842 connector and signals are not coming out.

The PAS laser enables for cells 0-4 should run on the 7842R (1) on DIO5-9.

(an aside but laser enable signals for the CRDS on the 6225 card now work)

**Comment by lo-co** [comment]
If the (1) is connector 1, then we are on the wrong connector.  Switching this now.

**Comment by lo-co** [comment]
Closing this as it is not a UI issue.
