### ISSUE TITLE
CRD and PAS laser enable signals

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#87]
This is very close to working now.  Signals are making it to the lasers and are almost having the desired effect in terms of switching them on and off. Here are the remaining requirements:

1) Invert behavior of all UI controls for CRD and PAS lasers. Note that 5V turns the lasers off and so the current UI controls are backwards

2) CRD red and blue laser controls need reversing. Currently the red crd laser control switches power on the two blue crd lasers and the blue crd laser ui control switches power on the red laser

**Comment by lo-co** [comment]
Closing this as it is a server side issue...Will open two issues for this on the server side.
