### ISSUE TITLE
UI control initialistation problem

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#89]
While testing the CRD laser digital pulse signal, it appears that the UI controls for the frequency are not initializing correctly.

E.g. on launching the UI the red lasers frequency is set to 1kHz. This value matches that shown in the exscalabar.ini file. However the actual frequency of the pulse coming out the PXI is 1.3kHz. When the user manually re-enters 1kHz in the control, the output waveform then changes to the 1kHz value. 

A similar issue is seen for the blue laser control (and maybe is a problem for other UI controls?)

Why could this be and can we fix it?

**Comment by lo-co** [comment]
Is this the same for both lasers, or just the red?  This is likely associated with lo-co/exscalabar_server#124.  Closing this as it is not an interface issue.
