### ISSUE TITLE
Scaling on time domain plots

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#99]
Can we add functionality to the time domain plots to stop them from autoscaling

**Comment by lo-co** [comment]
Should be there - ``Autoscale 1x`` will force an autoscale once at the current range.  More than this we are going to likely have to hold off for a bit as it is not a huge implementation, but it will require a little work.  What say you?

**Comment by lo-co** [comment]
So....Justin.  I think this is in the documentation for the UI (but maybe not easy to find).  You can use the mouse to change the scales.  ``left-click-drag`` down zooms the y-axis; ``left-click-drag`` right or left should zoom the x-axis.  To get back to the original settings, double ``left-click``.  

I will make sure the functionality above is there for all plots
